dt:
  print_time:                         True
  print_objects_info:                 False
  record_time:                        True
  record_objects_info:                True

  sub_image1_topic:                   /image1
  sub_image2_topic:                   /image2
  calibration_image_file:             calibration_image.yaml

  display_image_raw:                  False
  display_image_segmented:            True
  
  display_2d_modeling:                True
  display_gate:                       True
  
  display_3d_modeling:                True
  display_frame:                      True
  display_obj_state:                  True
  
  processing_mode: D # D - detection, DT - detection and tracking
  
  blind_update_limit:                 0
  frame_rate:                         10
  max_id:                             10000
