dt:
  print_time:                         True
  print_objects_info:                 False
  record_time:                        True
  record_objects_info:                True

  sub_image1_topic:                   /pub_rgb # RGB image
  sub_image2_topic:                   /pub_t # Thermal image
  calibration_image_file:             calibration_image.yaml

  display_image_raw:                  False
  display_image_segmented:            False
  
  display_2d_modeling:                False
  display_gate:                       False
  
  display_3d_modeling:                False
  display_frame:                      False
  display_obj_state:                  True
  
  display_vi_fusion:                  True
  
  processing_mode: D # D - detection, DT - detection and tracking
  modality: RGBT # RGB - RGB image, T - Thermal image, RGBT - Both
  
  blind_update_limit:                 0
  frame_rate:                         10
  max_id:                             10000
